### ISSUE TITLE
22

### ISSUE THREAD

**Issue by nicompte** [GerardMentor/test#35]

**Comment by GerardMentor** [comment]
@GerardTeam/tests: Hey!

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: Hey!

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: Hey!

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: Hey!
