### ISSUE TITLE
Test Doudou

### ISSUE THREAD

**Issue by nicompte** [GerardMentor/test#46]

**Comment by nicompte** [comment]
Test !

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.
