### ISSUE TITLE
dgsdqg

### ISSUE THREAD

**Issue by nicompte** [GerardMentor/test#51]

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.

**Comment by GerardMentor** [comment]
@GerardTeam/marketing, @GerardTeam/tests: this issue has been treated and needs review.

**Comment by GerardMentor** [comment]
@GerardTeam/Tests gsdqg
